# Generated by Django 3.0.5 on 2020-04-22 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hamburguesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('descripcion', models.TextField()),
                ('imagen', models.TextField()),
            ],
        ),
    ]
