# Generated by Django 3.0.5 on 2020-04-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburguesas', '0002_hamburguesa_ingredientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
